/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as AuthenticatedAmigosRouteImport } from './routes/_authenticated/amigos'
import { Route as AuthenticatedMenuRouteImport } from './routes/_authenticated/menu'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedPartidaMatchIdRouteImport } from './routes/_authenticated/partida.$matchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAmigosRoute = AuthenticatedAmigosRouteImport.update({
  id: '/amigos',
  path: '/amigos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenuRoute = AuthenticatedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartidaMatchIdRoute =
  AuthenticatedPartidaMatchIdRouteImport.update({
    id: '/partida/$matchId',
    path: '/partida/$matchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/amigos': typeof AuthenticatedAmigosRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/partida/$matchId': typeof AuthenticatedPartidaMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/amigos': typeof AuthenticatedAmigosRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/partida/$matchId': typeof AuthenticatedPartidaMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/_authenticated/amigos': typeof AuthenticatedAmigosRoute
  '/_authenticated/menu': typeof AuthenticatedMenuRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/partida/$matchId': typeof AuthenticatedPartidaMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacidad'
    | '/terminos'
    | '/amigos'
    | '/menu'
    | '/perfil'
    | '/ranking'
    | '/partida/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacidad'
    | '/terminos'
    | '/amigos'
    | '/menu'
    | '/perfil'
    | '/ranking'
    | '/partida/$matchId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/privacidad'
    | '/terminos'
    | '/_authenticated/amigos'
    | '/_authenticated/menu'
    | '/_authenticated/perfil'
    | '/_authenticated/ranking'
    | '/_authenticated/partida/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PrivacidadRoute: typeof PrivacidadRoute
  TerminosRoute: typeof TerminosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/amigos': {
      id: '/_authenticated/amigos'
      path: '/amigos'
      fullPath: '/amigos'
      preLoaderRoute: typeof AuthenticatedAmigosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu': {
      id: '/_authenticated/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partida/$matchId': {
      id: '/_authenticated/partida/$matchId'
      path: '/partida/$matchId'
      fullPath: '/partida/$matchId'
      preLoaderRoute: typeof AuthenticatedPartidaMatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAmigosRoute: typeof AuthenticatedAmigosRoute
  AuthenticatedMenuRoute: typeof AuthenticatedMenuRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedPartidaMatchIdRoute: typeof AuthenticatedPartidaMatchIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAmigosRoute: AuthenticatedAmigosRoute,
  AuthenticatedMenuRoute: AuthenticatedMenuRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedPartidaMatchIdRoute: AuthenticatedPartidaMatchIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PrivacidadRoute: PrivacidadRoute,
  TerminosRoute: TerminosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
